### ISSUE TITLE
A bug……

### ISSUE THREAD

**Issue by 227BaronChen** [lucidrains/alphafold2#17]
When I test the example code of usage, there is a "RuntimeError", it says "input value can be a scalar only when boundaries tensor dimension is 1, but we got boundaries tensor dim(4) and input value's dim(0) numel(1).", which confuses me.
![1611208738(1)](https://user-images.githubusercontent.com/61997568/105286230-d6dcb800-5bf0-11eb-83ce-adaa2a47e2b9.jpg)
Does anyone have a similar problem, if anyone can help me, I would be very grateful.

**Comment by hypnopump** [comment]
Will solve it in approx an hour

**Comment by 227BaronChen** [comment]
Nice! I'd appreciate that.

> Will solve it in approx an hour

**Comment by hypnopump** [comment]
Good, so a PR is on its way to be accepted. In the meantime, you can access the code at this fork: https://github.com/hypnopump/alphafold2 OR try the `mean` option for mds instead of the deafult `median` one. To do so, replca the line n25 in your file by:
```python3
distances, _, weights = center_distogram_torch(distogram, center="mean")
```
Hope this solves your issue. if you'd like to contribute to the development, you can join us in the `/alphafold` channel here: https://discord.gg/BddkRME

**Comment by 227BaronChen** [comment]
Maybe, the line n150 of the utils module needs to add ".cuda()" to ensure that all data is loaded in the GPU. But when I was testing, no matter whether the " center='mean' "was added or not, the error was always "RuntimeError: CUDA error: device-side assert triggered"

**Comment by 227BaronChen** [comment]
Maybe, the line n150 of the utils module needs to add ".cuda()" to ensure that all data is loaded in the GPU. But when I was testing, no matter whether the " center='mean' "was added or not, the error was always "RuntimeError: CUDA error: device-side assert triggered".
![image](https://user-images.githubusercontent.com/61997568/105337557-83c92c00-5c15-11eb-842f-bac2ed0e49d2.png)


> Good, so a PR is on its way to be accepted. In the meantime, you can access the code at this fork: https://github.com/hypnopump/alphafold2 OR try the `mean` option for mds instead of the deafult `median` one. To do so, replace the line n25 in your file by:
> 
> ```python
> distances, _, weights = center_distogram_torch(distogram, center="mean")
> ```
> 
> Hope this solves your issue. if you'd like to contribute to the development, you can join us in the `/alphafold` channel here: https://discord.gg/BddkRME

**Comment by hypnopump** [comment]
may you try now? on the forked repo. the idea was tested on cpu, but i think it should work now. there's always the `mean` alternative

**Comment by 227BaronChen** [comment]
Thank you for your prompt reply, but there is still a little problem, and I believe it will be solved soon.
`distances, _, weights = center_distogram_torch(distogram)`: 
![image](https://user-images.githubusercontent.com/61997568/105348413-42d81400-5c23-11eb-9ea9-2c28aa593df4.png)
`distances, _, weights = center_distogram_torch(distogram, center="mean")`: 
![image](https://user-images.githubusercontent.com/61997568/105348496-6307d300-5c23-11eb-82aa-617cf1413e94.png)

> may you try now? on the forked repo. the idea was tested on cpu, but i think it should work now. there's always the `mean` alternative

**Comment by 227BaronChen** [comment]
At the same time, may you add comments to this forked repo, people need to remove the ".cuda()" in the usage (if they want to test  it on cpu).

**Comment by hypnopump** [comment]
should be working now

**Comment by hypnopump** [comment]
wrt to the comments: This project is in active development so it's not a final version. However, running on CPU is not advised. It will take too much time and even with multicore execution, it's not feasable (for reference, the mds step alone might take approx 1-10 minuts per protein, depending on the size and the number of mirrors per protein). 
I'll set up a general device naming in the next PR

**Comment by hypnopump** [comment]
wrt to the `mean` issue: there was a mistake saying that `center_distogram_torch` supported batched inputs (batch, N, N, B). It does not. Make sure you pass a tensor with shape  (N, N, B)

**Comment by 227BaronChen** [comment]
It seems that there is still an index problem.

**Comment by hypnopump** [comment]
error trace?

**Comment by 227BaronChen** [comment]
![image](https://user-images.githubusercontent.com/61997568/105351200-32c23380-5c27-11eb-93f8-dfe774130d05.png)

> error trace?

**Comment by hypnopump** [comment]
should be solved

**Comment by 227BaronChen** [comment]
new error?
![image](https://user-images.githubusercontent.com/61997568/105351797-00650600-5c28-11eb-89d3-6b33f02b2446.png)

**Comment by hypnopump** [comment]
This function has been tested in `/tests/structure_utils_tests.ipynb` . Check you're passing the arguments in the same way (n_mirrors, N, N)

**Comment by 227BaronChen** [comment]
Okay, thank you for your patient guidance.
