### ISSUE TITLE
center_distogram_torch with center = 'median' breaks when tensors are on CUDA device

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/alphafold2#26]

**Comment by hypnopump** [comment]
does it too on cpu?

**Comment by hypnopump** [comment]
one seq, could it be the number of bins?
i can see in the test file that you're passing a 37-bin distogram and no custom distance bins. the assumed distances shape is 20-bins long

**Comment by lucidrains** [comment]
@hypnopump still seeing an error for center = 'median' :( i added a test, and as long as you can make it pass `python setup.py test` then it should be fine

**Comment by lucidrains** [comment]
@hypnopump oops, this should be in the other issue lol

**Comment by hypnopump** [comment]
aha okay then

**Comment by hypnopump** [comment]
i think this is solved now

**Comment by lucidrains** [comment]
![Screenshot from 2021-02-04 12-26-12](https://user-images.githubusercontent.com/108653/106951152-3ef8c700-66e4-11eb-8a05-770547b62a1f.png)

oh, unfortunately not

does it work on your machine?

**Comment by hypnopump** [comment]
oh i thought it was included in the tests. well, i'm doing a pr with a possible fix, but it needs to be checked. i still havent tested any component on a cuda machine.

**Comment by lucidrains** [comment]
@hypnopump no rush, you can try running it and developing in colab actually (if you lack a machine) - colab comes with a really nice code editor (and a terminal too!)

**Comment by hypnopump** [comment]
i have solved this and the `vocab+int2char` thing. will make a PR to the main brach later today with the changes

**Comment by hypnopump** [comment]
pr here: https://github.com/lucidrains/alphafold2/pull/32

**Comment by lucidrains** [comment]
awesome!
