### ISSUE TITLE
Output pdb file

### ISSUE THREAD

**Issue by 227BaronChen** [lucidrains/alphafold2#38]
What can I do if I want to input protein sequences and output pdb files based on your code?

**Comment by hypnopump** [comment]
A sample code for this situation will be added later today

**Comment by 227BaronChen** [comment]
Thanks a million.

**Comment by hypnopump** [comment]
Provided an example in the last commit! check it out in `train_end2end.py` --> the whole training code needs a brush, which will be done soon, but the example should be easy to follow
