### ISSUE TITLE
Question: Why are lengths of seq and msa same and different?

### ISSUE THREAD

**Issue by ychuhp** [lucidrains/alphafold2#45]
Hello, the lengths of seq and msa are same and different in different examples in the readme.
Am I not understanding something?

Thanks,

**Comment by lucidrains** [comment]
@ychuhp hello! the MSA used for alphafold2 is actually the raw MSA, and needs not be the same length as the primary sequence. the cross attention will sort it out

**Comment by ychuhp** [comment]
Thank you. Closing the issue.
