### ISSUE TITLE
I want use casp13 dataset.

### ISSUE THREAD

**Issue by Planet-KIM** [lucidrains/alphafold2#48]
- I want use casp13 dataset.
- And i want use covid-13 protein pdb file.(In this project)
- Please give me solutions.

**Comment by ychuhp** [comment]
I have been trying to do something similar to compare different methods.
Here is a nice package (from the readme) that can get the casp data for you.
https://github.com/jonathanking/sidechainnet

```
import sidechainnet as scn
d = scn.load(casp_version=12, thinning=30)
d['train']['seq'] #sequence
d['train']['crd] #coordinates
```
You would need to format the sequence and generate a msa for each sequence you want to test. Try hhblits for the msa.
