### ISSUE TITLE
How to use casp13 dataset & covid-13 protein sequence on this project.

### ISSUE THREAD

**Issue by Planet-KIM** [lucidrains/alphafold2#52]
- I want use casp13 dataset.
- And i want use covid-13 protein pdb file.(In this project)
- Please give me solutions.

**Comment by hypnopump** [comment]
You'll need the sequences, the MSAs and the coordinates for the CASP13 dataset for training (see [here](https://github.com/aqlaboratory/proteinnet) and [here](https://github.com/jonathanking/sidechainnet/#reproducing-sidechainnet) for how the datasets we're using were obtained)

To predict the covid protein, you'll need the sequence and the msa for it. Maybe once we have a model trained with esm embeddings, you can do a structure with only the sequence, but resolution will likely be worse than with msa

**Comment by Planet-KIM** [comment]
- Now i have covid-19 protein sequence(protein.faa file) file
- How to predict covid-19 protein? Please give me soultions.
- This project have predict method function?

**Comment by hypnopump** [comment]
This project is a work in progress so it's not ready for usage yet (we may notify you when it is - we estimate in the course of a month). In the meantime, you can look at implementations of AlphaFold1 ( [the official one](https://github.com/deepmind/deepmind-research/tree/master/alphafold_casp13), [a replication](https://github.com/dellacortelab/prospr), or mini projects [like this one by myself](https://github.com/hypnopump/MiniFold) ) or the trRosetta algorithm ([the official one](https://github.com/gjoni/trRosetta) and [an open source replication](https://github.com/lucidrains/tr-rosetta-pytorch))
