### ISSUE TITLE
the dimensions of coordinates in CASP12

### ISSUE THREAD

**Issue by zhangyi-taotao** [lucidrains/alphafold2#71]
@lucidrains Hi!  In the test_coor, there is code like:   assert coords.shape == (2, 16 * 14, 3), 'must output coordinates' .   What does “14“ here mean。In the model, num_backbone_atoms = 3, shouldn’t the coordinate dimension be（2,16 * 3, 3）。

**Comment by lucidrains** [comment]
@zhangyi-taotao hey yes, that is a bug indeed and i'll get around to fixing it today at the very latest tomorrow!

**Comment by lucidrains** [comment]
@zhangyi-taotao https://github.com/lucidrains/alphafold2#atoms let me know if that helps or not!

**Comment by zhangyi-taotao** [comment]
@lucidrains  Thank you very much for helping me answer my doubts！
