### ISSUE TITLE
ModuleNotFoundError: No module named 'invariant_point_attention'

### ISSUE THREAD

**Issue by jackli777** [lucidrains/alphafold2#83]
ModuleNotFoundError: No module named 'invariant_point_attention'

![image](https://user-images.githubusercontent.com/16830070/126600706-0746b163-d84f-4df1-af54-6f95c96d73ed.png)

**Comment by lucidrains** [comment]
@jackli777 hey! have you tried pip installing the package first? or `pip install invariant-point-attention`

**Comment by hypnopump** [comment]
we should consider adding it to package requirements so installation is done by default. Will definitely do so once this is more mature. Closing for now.
