### ISSUE TITLE
MSA attention gated problem

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/alphafold2#84]
Hi Phil:

Compare the 'gating' unit with the original algorithm:
https://github.com/lucidrains/alphafold2/blob/586792d738b9867d02b85a304c9b56091121b460/alphafold2_pytorch/alphafold2.py#L147

I thought gating here just missed a 'sigmoid()', please have a check.

Best,

**Comment by lucidrains** [comment]
@CiaoHe done https://github.com/lucidrains/alphafold2/releases/tag/0.4.13! :pray:
