### ISSUE TITLE
OuterMean block's  typo

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/alphafold2#86]
Hi, Luci:
Here, the original paper uses outer-product, but here uses outer-sum
https://github.com/lucidrains/alphafold2/blob/586792d738b9867d02b85a304c9b56091121b460/alphafold2_pytorch/alphafold2.py#L316

plz have a check, many thanks!

**Comment by hypnopump** [comment]
Hi there! Seems you've been taking a decent review at the code! I'd like to invite you to the discord server where the replication is being coordinated:  https://discord.gg/NNGTt4Vp . Hopefully we can get this done soon!

**Comment by lucidrains** [comment]
@CiaoHe thank you, this is bug number 3 you've caught :) :pray:

**Comment by lucidrains** [comment]
fixed in latest

**Comment by CiaoHe** [comment]
> Hi there! Seems you've been taking a decent review at the code! I'd like to invite you to the discord server where the replication is being coordinated: https://discord.gg/NNGTt4Vp . Hopefully we can get this done soon!

Hi, thanks for invitation, I'm already in lol
