### ISSUE TITLE
Maybe Inverse of the outgoing-attention and ingoing-attention here

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/alphafold2#88]
Hi Phil:

Haha, one similar issue here, I thought the outgoing-attention[ =  paper's `triangular gated self-attn around starting node`] should use `row-attention` since we start from a node `i` and propagate information to `j` and `k`. So, it's `ij,ik ->jk`, maybe we should use `row-attention`. 
Likewise, in the ingoing-attention, we should use `col-attention` (`ij,kj->ki`)
https://github.com/lucidrains/alphafold2/blob/a78352805204d47851f3b972e3d5c142ec7a3b49/alphafold2_pytorch/alphafold2.py#L361-L362

Best,

**Comment by lucidrains** [comment]
ohh true, should be fixed in https://github.com/lucidrains/alphafold2/commit/2c574801bab437b25018c2591fbc06fe17dee06c
