### ISSUE TITLE
pairwise_repr should be used in rowAttention

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/alphafold2#89]
Hi, Phil

https://github.com/lucidrains/alphafold2/blob/a78352805204d47851f3b972e3d5c142ec7a3b49/alphafold2_pytorch/alphafold2.py#L400-L401

according to the original paper,  (Algorithm 6, line2-4), the pairwise_repr(bias) used in `MSARowAttentionWithPairBias` instead of `MSAColumnAttention`. plz have a check

Best,

**Comment by lucidrains** [comment]
https://github.com/lucidrains/alphafold2/commit/2c574801bab437b25018c2591fbc06fe17dee06c :+1:
