### ISSUE TITLE
Example script of an end-to-end prediction from FASTA sequence to 3D pdb

### ISSUE THREAD

**Issue by h-midlothian** [lucidrains/alphafold2#94]
Thanks for your codes. I just wonder if you could provide a script of the prediction process with a FASTA sequence as input and predicted PDB file as output; if not just give me some hint please. Thanks in advance.

**Comment by hypnopump** [comment]
Not ready yet. You could take a look at ColabFold in the meantime. Once we have something ready for this application we'll tell you.

**Comment by h-midlothian** [comment]
@hypnopump  OK, thanks a lot.
