### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/alphafold2#95]
Hi Phil and Eric @hypnopump 

I'm not familiar with the operations on protein structure or whatever :(, but here I wonder is it a mistake when indexing:

https://github.com/lucidrains/alphafold2/blob/521415676df4043ed101a882d0eae7a659c774d0/alphafold2_pytorch/utils.py#L702

Perhaps it should be `new_coords[s,:-padding or None, i]` since in the inner loop it just constructs the `s`-th sequence sidechain's coords.

Best,

**Comment by hypnopump** [comment]
Oh yes! Hidden bug (the function was only used with one sequence so the error ran unnoticed).

In general, the utils need an update (which i do have locally but havent pushed). I'll be updating them in the following days.

**Comment by CiaoHe** [comment]
> Oh yes! Hidden bug (the function was only used with one sequence so the error ran unnoticed).
> 
> In general, the utils need an update (which i do have locally but havent pushed). I'll be updating them in the following days.

Thanks a lot eric!

**Comment by lucidrains** [comment]
@CiaoHe thanks for all the code reviews!
